//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DiamondJam.Math
{
	public struct GemMove
	{
		public IntVector2 from;
		public IntVector2 to;

		public GemMove(IntVector2 from, IntVector2 to){
			this.from = from;
			this.to = to;
		}

		public override string ToString(){
			return "From "+from+" to "+to;
		}
	}
}

